DOCKER-211 Always use standard parameters for curl commands
liferay/liferay-docker pull request #131
Opened 2023-08-23 09:34 UTC by LFRAMIT

Do Not Merge

2023-08-23 09:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/liferay/liferay-docker?pullRequest=131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/liferay/liferay-docker?pullRequest=131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/liferay/liferay-docker?pullRequest=131) it.</sub>

2023-08-23 09:38 UTC, LFRAMIT commented
#build_x1e4

2023-08-24 10:07 UTC, ZoltanTakacs requested changes
1. Please make sure that the parameters are listed alphabetically, especially take care of `--silent --show-error` ones. 
2. In order to verify it, please build docker images locally by following the guideline on https://liferay.atlassian.net/wiki/spaces/DSOH/pages/1970700397/Liferay+Docker+images

2023-08-24 12:01 UTC, LFRAMIT commented
Changes Requested. Closing this PR.

2023-08-24 12:01 UTC, closed without merging